# ~~~~~~~~ General ~~~~~~~~

batch_size:             256
seed:                   1
print_per_step_summary: False

# ~~~~~~~~ WandB ~~~~~~~~

wandb_project:  'dendritic-snn'
wandb_mode:     'offline'

# ~~~~~~~~ Checkpoints ~~~~~~~~

checkpoints:                  True
checkpoint_unit:              'Epoch' # ['Step', 'Epoch']
checkpoint_strategy:          'All'   # ['All', 'Best']
checkpoint_period:            1
checkpoint_start_after:       5
units_to_train:               150

average_last_after_best_checkpoints:  False
average_last_checkpoints:             False
best_checkpoint_indicator:            'search_acc'
best_checkpoint_indicator_goal:       'max' # ['min', 'max']

# ~~~~~~~~ Criterions, Scores, Optimizer ~~~~~~~~

average_gradients:         False
allow_none_type_gradients: True

criterions: [
  {
    score_type: 'LMRegressionLoss',
    input_keys: ['tgt', 'mask', 'label_mask'],
    reduce_type: 'avg_counts',
  }
]

scores: [
  {
    score_type: 'LMAccuracy',
    input_keys: ['labels', 'label_seqs', 'lens'],
    reduce_type: 'avg_counts'
  },
  {
    score_type: 'LMTrueAccuracy',
    input_keys: ['inp', 'lens', 'labels'],
    reduce_type: 'avg_counts'
  },
  {
    score_type: 'FiringRate',
    input_keys: ['mask', 'all_spikes'],
    reduce_type: 'avg_counts'
  }
]

optimizers: [
  {
    optim_type: 'Adam',
    param_groups: [
      {
        name: 'weights',
        weight_decay: 0.00001,
        init_lr: 0.01,
      },
      {
        name: 'batchnorms',
        weight_decay: 0,
        init_lr: 0.01,
      }
    ],
    lr_scheduler: {
      lr_type: 'Constant',
      lr:  0.01
    }
  },
  {
    optim_type: 'Adam',
    param_groups: [
      {
        name: 'delays',
        weight_decay: 0,
        init_lr: 0.1
      }
    ],
    lr_scheduler: {
      lr_type: 'CosineAnnealing',
      tmax: 150,
      per_step: False
    }
  }
]

# ~~~~~~~~ Model ~~~~~~~~

model:          'delayLmLIF'
model_input:    ['inp', 'tgt', 'lens', 'labels']

n_layers:       2
hidden_size:    128
threshold:      1. # 0.37
dropout:        0.4 
beta_init_min:  0.4 # note: before sigmoid
beta_init_max:  0.9 # note: before sigmoid
cell_type:      'original' # ['soft', 'hard', 'original']

# Delays
init_tau:                   10.05
max_delay:                  35
sigma_init:                 12
sigma_decrease_final_epoch: 150

# Spikoder
spikoder:             'sinusoidal' # ['linear', 'sinusoidal']
sample_labels:        True
resample_every_step:  False
encoding_length:      10

# SpecialTokenEncoder
special_token_fr: 0.5

# Loss
similarity_function:    'activity' # ['neuron', 'activity']
clamp_tgt_to_one:       True
lambda_data:            0.
lambda_label:           1.

# Search
lm_search_algorithm: 'greedy' # ['greedy']

# ~~~~~~~~ Sweep ~~~~~~~~

do_sweep: True
sweep_configuration: {
  method: 'random',
  count: 200,
  parameters: {
    seed: {values: [0, 41]}, #80420, 90, 172]},
  }
}