# ~~~~~~~~ General ~~~~~~~~

batch_size:     256
seed:           0

# ~~~~~~~~ WandB ~~~~~~~~

wandb_project:  'dendritic-snn'
wandb_mode:     'offline'

# ~~~~~~~~ Checkpoints ~~~~~~~~

checkpoints:                  True
checkpoint_unit:              'Epoch' # ['Step', 'Epoch']
checkpoint_strategy:          'All'   # ['All', 'Best']
checkpoint_period:            1
checkpoint_start_after:       5
units_to_train:               150

average_last_after_best_checkpoints:  False
average_last_checkpoints:             False
best_checkpoint_indicator:            'lm_acc'
best_checkpoint_indicator_goal:       'max' # ['min', 'max']

# ~~~~~~~~ Criterions, Scores, Optimizer ~~~~~~~~

average_gradients:         False
allow_none_type_gradients: True

criterions: [
  {
    score_type: 'LMRegressionLoss',
    input_keys: ['tgt'],
    reduce_type: 'avg_counts',
    loss_function: 'neuron' # ['neuron', 'activity']
  }
]

scores: [
  {
    score_type: 'LMAccuracy',
    input_keys: ['labels', 'label_seqs'],
    reduce_type: 'avg_counts'
  }
]

optimizers: [
  {
    optim_type: 'Adam',
    param_groups: [
      {
        name: 'weights',
        weight_decay: 0.00001,
        init_lr: 0.01,
      },
      {
        name: 'norms',
        weight_decay: 0,
        init_lr: 0.01,
      }
    ],
    lr_scheduler: {
      lr_type: 'Constant',
      lr: 0.01
    }
  }
]

# ~~~~~~~~ Model ~~~~~~~~

model:          'lmLIF'
model_input:    ['data', 'labels', 'sos']

n_layers:       2
hidden_size:    256
threshold:      0.37
dropout:        0.4
beta_init_min:  0.4 # note: before sigmoid
beta_init_max:  0.9 # note: before sigmoid
cell_type:      'hard' # ['soft', 'hard']

# Spikoder
spikoder: 'random_fixed' # ['random_fixed']
encoding_length: 10


# SpecialTokenEncoder
special_token_fr: 0.5

# ~~~~~~~~ Sweep ~~~~~~~~

do_sweep: True
sweep_configuration: {
  method: 'random',
  count: 200,
  parameters: {
    seed: {values: [0, 41, 80420, 90, 172]},
  }
}